# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

php:
  - 7.0

env:
  - DB=mysql

services:
  - mysql
  
matrix:
  include:
    - php: 7.0
      env: WITH_COVERAGE=true

before_script:
  
script:
 - ./tools/test.sh 
 
