<?php
DEFINE('REGIST_TITLE','Új felhasználó regisztrálása');
DEFINE('REGMOD','Regisztráció módja');
DEFINE('UKLOGIN','magyarorszag.hu ügyfélkapu');
DEFINE('WEB','Hagyományos WEB email-es aktíválással');
DEFINE('NICK','Bejelentkezési név');
DEFINE('PSW','Jelszó');
DEFINE('PSW_REPEAT','Jelszó ismét');
DEFINE('VALID_NAME','Valódi név');
DEFINE('EMAIL','E-mail');
DEFINE('AUTHENTIC','Hitelesített');
DEFINE('AVATAR','Avatar kép URL vagy "gravatar"');
DEFINE('PUBINFO','Egyébb információk (pl. nem, életkor, szakma, lakhely stb) Figyelem ezeket az infokat mindenki láthatja aki a web oldalra látogat');
DEFINE('USRREG_HELP','A * -al jelölt adatokat ki kell tölteni');
DEFINE('USRPROFILE_HELP','Ha a két jelszót üressen hagyja akkor a jelszó nem változik.');
DEFINE('NICK_REQUED','Bejelentkezési nevet meg kell adni.');
DEFINE('PSW_REQUED','Jelszót meg kell adni.');
DEFINE('NAME_REQUED','Valódi nevet meg kell adni.');
DEFINE('EMAIL_REQUED','E.mail címet meg kell adni.');
DEFINE('PSWS_NOT_EQUALS','A két jelszó nem azonos.');
DEFINE('PSWS_SORT','A jelszó túl rövid (min 6 karakter)');
DEFINE('USER_RIGHTS','Jogosultágok');
DEFINE('NICK_EXISTS','Ez a bejelntkezési név már használatban van.');
DEFINE('EMAIL_EXISTS','Ezzel az email címmel már regisztráltak.');
DEFINE('USER_SAVED','Adatok tárolva');
DEFINE('NEW_USER_SAVED','Adatok tárolva, aktiváló email lett elküldve.');
DEFINE('FALSE_LOGIN','HIbás belépési adatok.');
DEFINE('TOO_MANY_FALSELOGIN','Túl sok hibás kisérlet. Fiók 10 órára blokkolva');
DEFINE('ACCOUNT_IS_BLOCKED','Ez a fiók blokkolva van.');
DEFINE('FORGET_MY_PASSWORD','Elfelejtettem a jelszavamat.');
DEFINE('FORGET_MY_NICK','Elfelejtettem a bejelentkezési nevemet');
DEFINE('GET_ACTIVATE_EMAIL','Aktiváló email újra küldése');
DEFINE('ACCOUNT_ACTIVATED','Fiók aktiválva.');
DEFINE('FALSE_ACTIVATION','Hibás aktiválási kód');
DEFINE('UKLOGIN_LOGIN','Uklogin (Ügyfélkapus) belépés');
DEFINE('EMAIL_SENDED','Levél elküldve.');
DEFINE('SURE_REMOVE_ACCOUNT','Biztos törölni akarod ezt a fiokt? Igen válasz esetén a továbbiakban nem lehet ezzel a fiokkal bejelentkezni!');
DEFINE('ACCOUNT_REMOVED','Fiók törölve');
DEFINE('USERS_LIST','Felhasználók listája');
?>
